import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/shared/styles/globals.css";
import QueryProvider from "../shared/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Rebellion",
  description: "Generated by Rodion",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={"ru"} suppressHydrationWarning>
      <body className={inter.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
